### ISSUE TITLE
gotcha with using GitHub package registry for hosting pre-built images

### ISSUE THREAD

**Issue by softprops** [ScottBrenner/cfn-lint-action#10]
I just tried using the prebuilt docker image to get access to the recent problem matcher update and realized you need to authenticate docker with the package registry before interacting with the image.  This would be fine except that GitHub pre-pulls any dockerized image when preparing the workflow before any actions run. 

This creates a situation where the workflow job preparation fails because the job hasn't had an opportunity to authenticate docker with the package registry yet.

<img width="889" alt="Screen Shot 2019-12-26 at 12 58 46 PM" src="https://user-images.githubusercontent.com/2242/71485572-b371ee80-27df-11ea-9be1-ac26807dd479.png">

I'm not sure if there are any work arounds aside publishing to a public docker hub registry where authentication is not needed.

**Comment by ScottBrenner** [comment]
Odd, thanks for the heads-up! Addressed with https://github.com/ScottBrenner/cfn-lint-action/commit/9c34b58f7ad2e05fa61ee7b8e10e6cdef0803b1e.

**Comment by softprops** [comment]
Hot dang. Thanks for the fast turn around. I started a question in the community forum to see if this wasn't something others had run into as well.

https://github.community/t5/GitHub-Actions/Authenticating-docker-with-package-registry-for-hosted-docker/m-p/42052#M4846

 Thanks for the fix
