### ISSUE TITLE
"Testing with CFN Lint Version & Command" job failing for windows-201{6,9}

### ISSUE THREAD

**Issue by ScottBrenner** [ScottBrenner/cfn-lint-action#141]
**Describe the bug**
The "Testing with CFN Lint Version & Command" job recently began failing for both `windows-2016` and `windows-2019`:

- https://github.com/ScottBrenner/cfn-lint-action/runs/5011679025?check_suite_focus=true#step:7:74
- https://github.com/ScottBrenner/cfn-lint-action/runs/5011639730?check_suite_focus=true#step:7:74

**GitHub Actions Runner configuration (please complete the following information):**
 - OS: `windows-2016` and `windows-2019`
 - Inputs: `C:\Users\RUNNER~1\AppData\Local\Temp\setup-cfn-lint-7KAzWl\bin\cfn-lint.exe -t ./examples/template.yml`
 - Version: https://github.com/ScottBrenner/cfn-lint-action/runs/5011679025?check_suite_focus=true#step:6:5

**Additional context**
https://stackoverflow.com/a/58959576 suggests updating Node?

**Comment by NickLiffen** [comment]
I think it could be to do with this:

https://github.com/ScottBrenner/cfn-lint-action/blob/main/lib/utils/helpers.js#L10

Maybe `Win32` is no longer the right option 🤔

**Comment by NickLiffen** [comment]
@ScottBrenner we are[ running Node 12](https://github.com/ScottBrenner/cfn-lint-action/blob/main/action.yml#L17), maybe changing this to `node16` could do it.

**Comment by ScottBrenner** [comment]
Attempted `node16` in https://github.com/ScottBrenner/cfn-lint-action/pull/152, no luck. `win32` seems right from https://nodejs.org/api/os.html#os_os_platform

**Comment by NickLiffen** [comment]
I will try and get around to this Monday 👍

**Comment by ScottBrenner** [comment]
Seems to be passing now, odd
