### ISSUE TITLE
Usage workflow example results in syntax error

### ISSUE THREAD

**Issue by jkataja** [ScottBrenner/cfn-lint-action#15]
Adding the sample workflow template, I received the error:

> Check failure on line 17 in .github/workflows/main.yml
> GitHub Actions
> / .github/workflows/main.yml
> Invalid workflow file
> You have an error in your yaml syntax on line 17

LIne 17 reads:
```
        args: **/*.yaml
```
I was able to make this action work for jkataja/cfn-foldingathome by hard-coding the template filename.

**Comment by ScottBrenner** [comment]
Looks like your file has extension `.yml`, so that example argument won't catch it.

**Comment by Jlrine2** [comment]
I don't think this was the issue, beginning a string with an asterisks is invalid yaml, it should be quoted, I opened a PR to resolve this issue.
