### ISSUE TITLE
/bin/sh: pip3: not found

### ISSUE THREAD

**Issue by deleugpn** [ScottBrenner/cfn-lint-action#18]
Since yesterday I noticed all my GH actions are failing due to pip3 not found. I think this might be related to alpine 3.12 being tagged?

**Comment by ScottBrenner** [comment]
Where are you seeing this error? I wasn't able to reproduce it:
```
$ docker build . --file Dockerfile --tag image
...
Step 1/17 : FROM python:3.8-alpine
...
Successfully tagged image:latest
$ docker run --entrypoint cfn-lint image -v
cfn-lint 0.33.0
```

**Comment by deleugpn** [comment]
I noticed that `master` and tag 1.5.0 diverge and the issue is happening when using 1.5.0

**Comment by ScottBrenner** [comment]
Oh, the 1.5.0 tag is outdated - I've just tagged https://github.com/ScottBrenner/cfn-lint-action/releases/tag/1.6.0.
