### ISSUE TITLE
Automatically using latest cfn-lint caused breaking change

### ISSUE THREAD

**Issue by Alex-Dettinger** [ScottBrenner/cfn-lint-action#209]
**Describe the bug**
This action automatically used the latest version of cfn-lint, 0.63.1. This broke the action because DB endpoint attributes are not defined in the same way.

**To Reproduce**
1. Run the action with the latest version of cfn-lint

**Expected behavior**
For the action to run without error

**Screenshots**
![Screen Shot 2022-08-30 at 4 38 27 PM](https://user-images.githubusercontent.com/86626632/187548296-ff5cae80-775e-4f6d-8ac4-dc664608fa01.png)

**GitHub Actions Runner configuration (please complete the following information):**
 - OS: ubuntu-20.04
 - Inputs: none (run on merge)

**Comment by ScottBrenner** [comment]
Is this not an issue with `cfn-lint` itself? The version used can be specified following https://github.com/ScottBrenner/cfn-lint-action#usage

**Comment by Alex-Dettinger** [comment]
Ah, thank you. Specifying the version of the underlying `cfn-lint` package is what I need
