### ISSUE TITLE
Bump action runtime to Node 16

### ISSUE THREAD

**Issue by grollinger** [ScottBrenner/cfn-lint-action#224]
**Describe the bug**
Recently, GitHub [deprecated](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) the `node12` action runtime version and started producing warnings when an action using that runtime version is used in a workflow.

**To Reproduce**
1. Use `cfn-lint-action` in a workflow run
2. Observe warnings in the "Summary" view of the workflow run

**Expected behavior**
No deprecation warnings 😄 

**Actual behavior**
GitHub produces warnings like the following:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: scottbrenner/cfn-lint-action
```

**Comment by NickLiffen** [comment]
This is being solved here: https://github.com/ScottBrenner/cfn-lint-action/pull/225

**Comment by ScottBrenner** [comment]
➡️ https://github.com/ScottBrenner/cfn-lint-action/releases/tag/v2.2.8

**Comment by ScottBrenner** [comment]
Seeing similar messages in https://github.com/ScottBrenner/cfn-lint-action/pull/235 now 👀
