### ISSUE TITLE
Reconsider publishing a prebuild images

### ISSUE THREAD

**Issue by softprops** [ScottBrenner/cfn-lint-action#23]
Please reconsider publishing a prebuilt image to a public docker registry. In one of my projects that use this action all other linting happens in seconds for a large repository. Since we're no longer able to use a pre-built docker image for this action, we have to wait at least a minute _before_ the action can start doing any work. This build time was previous amortized with a prebuilt image which greatly reduced the feedback cycle time. 

<img width="1082" alt="Screen Shot 2020-10-15 at 12 09 37 AM" src="https://user-images.githubusercontent.com/2242/96076230-d6f34c00-0e7a-11eb-8cb3-ac1ae1637cf7.png">

**Comment by ScottBrenner** [comment]
https://github.com/users/ScottBrenner/packages/container/package/cfn-lint-action

**Comment by softprops** [comment]
Thanks for this! This reduced the feedback cycle from over a minute to about 5 seconds
