### ISSUE TITLE
Feature: Custom Lint Files

### ISSUE THREAD

**Issue by NickLiffen** [ScottBrenner/cfn-lint-action#27]
As a developer, I would like to append custom rules to this action, so I can run specific actions that are only applicable to the company I work for.

In a perfect work, I would be able to specify the repository, ref (branch) and path 💯

**Comment by NickLiffen** [comment]
@ScottBrenner 👋 How open would you be to a slight restructuring of the architecture of this application? Right now it's all in oneDockerfile`, I can see us expanding outside to use something like [this](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action). 

It would mean we could add some unit tests and also have some more luxury with the GitHub Octokit Library. E.G in this issue, I can reference other repositories outside the scope of the action it runs in. 

I am happy to do the work, but understand you are the maintainer so would like your thoughts. 

Personally, everything in the `Dockerfile` somewhat limits us a bit with the potential of this action. However, your thoughts would be great 👍

**Comment by NickLiffen** [comment]
Again, I would be happy to do all the work 💯 and will get you to review it. 

The cloud formation linter has great config options, and I think we could honour that better with the JS Option over native `Dockerfile`. Thanks. Happy to chat about it in this issue if you like.

**Comment by ScottBrenner** [comment]
Let's do it! I've no experience developing in JavaScript unfortunately so I wouldn't be able to assist much, but I'm certainly open to it.

**Comment by NickLiffen** [comment]
Thanks @ScottBrenner 💯 Could you assign me `write` access, please? It's easier to test in this repo, you can protect the `master` branch and assign reviews to make sure you review before anything goes in 👍  If that's okay, would be a little easier then forking? Thanks 👍

**Comment by ScottBrenner** [comment]
Sure, but what's the advantage of working in this repository over a fork? not familiar myself

**Comment by NickLiffen** [comment]
Sory @ScottBrenner I am just getting to this 👍 I am ready to raise a pull request if you are good to review 👍 ?

**Comment by ScottBrenner** [comment]
Sure! 👍🏻

**Comment by NickLiffen** [comment]
@ScottBrenner pull request raised 👍 would love your feedback 🌷
