### ISSUE TITLE
Update Node.js version 

### ISSUE THREAD

**Issue by Gershon-A** [ScottBrenner/cfn-lint-action#360]
**Is your feature request related to a problem? Please describe.**
Node 16 has reached its [end of life](https://github.com/nodejs/Release/#end-of-life-releases), prompting us to initiate its deprecation process for GitHub Actions. Our plan is to transition all actions to run on Node 20 by Spring 2024. We will actively monitor the migration's progress and gather community feedback before finalizing the transition date. Starting October 23rd, workflows containing actions running on Node 16 will display a warning to alert users about the upcoming migration.
**Describe the solution you'd like**
Upgrade node version to latest  GitHub supported.

**Describe alternatives you've considered**
Upgrade node version to latest  GitHub supported.

**Additional context**
Node.js 16 actions are deprecated

**Comment by ScottBrenner** [comment]
Thanks for reporting, released in https://github.com/ScottBrenner/cfn-lint-action/releases/tag/v2.4.0.
