### ISSUE TITLE
Unable to resolve action `ScottBrenner/cfn-lint-action@master`, unable to find version `master`

### ISSUE THREAD

**Issue by NickLiffen** [ScottBrenner/cfn-lint-action#37]
Getting the following error:

```
Unable to resolve action `ScottBrenner/cfn-lint-action@master`, unable to find version `master`
```

@ScottBrenner we may want to revert back to `master`, or create a separate branch called `master` and then when/if we release #33 why don't we bring in the removal of the `master` branch with this breaking change? (If that makes sense? Thoughts?

**Comment by ScottBrenner** [comment]
Oops, reverted the branch name 😰

**Comment by hoxu** [comment]
@ScottBrenner looks like the `master` branch is still missing.

Renaming the branch for a repository that is referenced from god knows how many places is a very bad idea.

**Comment by ScottBrenner** [comment]
Normally I would agree, but https://github.com/ScottBrenner/cfn-lint-action/commit/15421eb7a3008bd51ffca8ee8fa51296457aa679 introduced breaking changes - regardless of branch name, the Action would and did break for anyone not version pinning to a specific release.

**Comment by hoxu** [comment]
One option would be to leave `master` pointing to the last commit before breaking changes. That would allow people to upgrade to the recommended v2 tagging on their leisure. GitHub will show the default branch on next visit, at which point they would discover about v2.

**Comment by hoxu** [comment]
Another consideration: organizations that use whitelisted actions can't make this upgrade without inertia:

> scottbrenner/cfn-lint-action@v2 is not allowed to be used in XXX. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, verified in the GitHub Marketplace or match the following XXX

**Comment by ScottBrenner** [comment]
Fair points, I've just revived the "old" Action in https://github.com/ScottBrenner/cfn-lint-action/tree/master - but know that it's deprecated! 😉

**Comment by hoxu** [comment]
Thanks! This will allow us to run the workflow until we get v2 whitelisted :)
