### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by cfarrend** [ScottBrenner/cfn-lint-action#4]
Hi,

Looks like there is a recent issue with the Dockerfile steps:
```
Step 11/16 : RUN apk --no-cache add python3
 ---> Running in d867ceae67d9
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz: No such file or directory
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  python3 (missing):
    required by: world[python3]
The command '/bin/sh -c apk --no-cache add python3' returned a non-zero code: 1
##[warning]Docker build failed with exit code 1, back off 1.371 seconds before retry.
/usr/bin/docker build -t 10865d:152429e9655543f5bb8dcb63c63feb68 "/home/runner/work/_actions/ScottBrenner/cfn-lint-action/1.1.0"
```

I have been looking at some solutions to fix the issue as it can be produced locally, it seems that the URL http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/ has disappeared, `apk update` didn't fix it either.

Should we consider perhaps switching our Docker image to use something like `python:3.7-alpine` and not requiring the need to install python?

**Comment by ScottBrenner** [comment]
Odd, thanks for opening the issue! Was able to produce locally, fixed with https://github.com/ScottBrenner/cfn-lint-action/commit/c06e88d1d0decadb4297f6d46549b41ed2800619

> perhaps switching our Docker image to use something like `python:3.7-alpine`

Not a bad idea, but the image ends up being 50+ MB bigger compared to how it is currently - best to keep it as small as possible.

**Comment by ScottBrenner** [comment]
New/fixed version published to GitHub Marketplace - https://github.com/marketplace/actions/cfn-lint-action

**Comment by cfarrend** [comment]
Thanks @ScottBrenner, this fixed the issue 👍
