### ISSUE TITLE
feat: Problem Matchers

### ISSUE THREAD

**Issue by ScottBrenner** [ScottBrenner/cfn-lint-action#40]
https://github.com/ScottBrenner/cfn-lint-action/commit/4e7c712c4d5e271500b8ad3d714bf09eef6e5a58 previously introduced Problem Matchers to this Action, but this functionality was removed with https://github.com/ScottBrenner/cfn-lint-action/commit/15421eb7a3008bd51ffca8ee8fa51296457aa679#diff-efc0e1791ad6067603d6250b9eca6bfa0159eb4f7ce6f65b5ffd68273a179117.

As discussed in https://github.com/ScottBrenner/cfn-lint-action/pull/33/files#r615433016:

>From https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md
> Problem Matchers are a way to scan the output of actions for a specified regex pattern and surface that information prominently in the UI
>
> This will display linting errors inline on pull requests, see the image in ~https://github.com/ScottBrenner/cfn-lint-action#github-action-for-cloudformation-linter~ https://github.com/ScottBrenner/cfn-lint-action/blob/90f970711aa1b19575dd9522d2340c5bca6df803/screenshot.png for an example.
>
> Might have to defer to original implementor @softprops regarding functionality, but in addition to this `cfn-lint.json` file we'll need something similar to https://github.com/ScottBrenner/cfn-lint-action/commit/4e7c712c4d5e271500b8ad3d714bf09eef6e5a58#diff-6f9d41d046756f0ddc2fcee0626bdb50100d12b88f293734eff742818e03efa2R7 looks like.

**Comment by softprops** [comment]
> Good question. I actually didn't know what this done. We could get this working again by simply adding the file back in and it would honour the files existence and the cfn-lint package would use it. However, I honestly didn't know what this was 🤔 @ScottBrenner could you explain? If it's needed all we need to do it re-commit it back in to the root of the action and copy it over to the $PATH I think

aw shucks this was really useful. I can take a look at this again

we managed installing this before with [an echo command](https://github.com/actions/toolkit/blob/fc005283374f1cea5e03ea1caf959cd9ff12fdc2/docs/commands.md#problem-matchers) but we should be able to do it in the update java script example as well. Here's an example from the[ setup-python action](https://github.com/actions/setup-python/blob/dc73133d4da04e56a135ae2246682783cc7c7cb6/src/setup-python.ts#L28-L29)

**Comment by NickLiffen** [comment]
I am happy to take a look at this btw if you need 👍 I don't really know what it does but happy to help to get it done if required 👍
