### ISSUE TITLE
v2 doesn't work, v2.0.0 does ... Investigating. 

### ISSUE THREAD

**Issue by NickLiffen** [ScottBrenner/cfn-lint-action#41]
Trying to work out why `v2` doesn't work by `v2.0.0` works 🤔 

When looking at other actions, such as [cache](https://github.com/actions/cache) it does the same as this action and works perfectly 🤔 so debugging now 🤔

**Comment by javs-perez** [comment]
running into the same issue.

**Comment by javs-perez** [comment]
I think the `cache` example has a `v2` tag. 

![image](https://user-images.githubusercontent.com/9657582/115278822-2a34a880-a103-11eb-8c6f-8c38dd03cd91.png)

**Comment by NickLiffen** [comment]
Ahhh, so maybe we need a `v2` here 🤔 Maybe that's a catch-all and they release all `v2` releases under a `v2` tag and a `v2.x.x` tag 🤔 This is interesting! I think that's the case! 

@ScottBrenner for now let's go ahead and create a `v2` tag and then maybe we come up with an automated way to do 2 deployments on every release. One to the `v2` tag and one to a `v2.x.x.` tag. Thoughts?

**Comment by ScottBrenner** [comment]
Yeah, that sounds like the right approach. Will tag a `v2` shortly

**Comment by NickLiffen** [comment]
Amazing 👍 no rush once the v2 tag is out. We can close out this issue once it's done and I think opening a new one to support multi deployments 💯 I see we are using your action `scottbrenner/generate-changelog-action@master` here. It would be great is this action could support such a feature but let's chat in the other issue 👍

**Comment by ScottBrenner** [comment]
https://github.com/ScottBrenner/cfn-lint-action/releases/tag/v2

**Comment by javs-perez** [comment]
Thank you all!
