### ISSUE TITLE
Discussion around what features should go into the v2.x.x release

### ISSUE THREAD

**Issue by NickLiffen** [ScottBrenner/cfn-lint-action#45]
Keen to understand what people want when it comes to consuming this action within their workflows. I have started a discussion around possible features that **could** be included within this major release, but want to understand what would be most valuable. 

If you are interested in contributing ideas/helping out, please head over to the [Feature Releases for Version 2.x.x](https://github.com/ScottBrenner/cfn-lint-action/discussions/44) discussion. 

**NOTE:** Any issues and bugs found should continue to follow the standard process of logging issues within this repository and not within the discussion above. The  [Feature Releases for Version 2.x.x](https://github.com/ScottBrenner/cfn-lint-action/discussions/44) discussion is simply meant to discuss and collaborate on ideas for the future.

**Comment by ScottBrenner** [comment]
Closing in favor of https://github.com/ScottBrenner/cfn-lint-action/discussions/44
