### ISSUE TITLE
Depreciation of <2 Release

### ISSUE THREAD

**Issue by NickLiffen** [ScottBrenner/cfn-lint-action#55]
@ScottBrenner I think it would be a good idea to start to set a deprecation notice for the old version 👍 It's been a while, I think we should update the README informing people that the old version won't work past June 15th let's say (just an example). We are feature complete with v1, which means all use cases being used in v1 will work in v2, for orgs that "enable" actions, I think giving them another month or something may be useful 👍 

Just a thought. Welcome your ideas.

**Comment by NickLiffen** [comment]
@ScottBrenner love the idea! Maybe there is something we can do, I have only used Docker for basic docker images so an no expert here. I can do some digging, but is this something you know we can do? 🤔

**Comment by ScottBrenner** [comment]
Should be easy enough to add an `echo "please update"` to https://github.com/ScottBrenner/cfn-lint-action/blob/master/entrypoint.sh, altho it wouldn't be super visible.
