### ISSUE TITLE
Publish a prebuilt container package for v2

### ISSUE THREAD

**Issue by barryhagan** [ScottBrenner/cfn-lint-action#85]
In #23 a prebuilt docker container was created to reduce the time it takes to run this GitHub action.  Can you publish a package for v2?  Currently the latest available package is still from the `master` branch.

**Comment by NickLiffen** [comment]
Hey @barryhagan 👋 thanks for the issue :) can you not reference the tag? Versus referencing the branch?

**Comment by barryhagan** [comment]
I can, but it was nice having a container prebuilt for both speed and consistency across runs. It does seem that v2 starts much faster than v1 did when not using the package, so maybe the question is if you are deprecating the prebuilt containers from here:  https://github.com/ScottBrenner/cfn-lint-action/pkgs/container/cfn-lint-action ?

i.e. there will never be something like this:

`uses: docker://ghcr.io/scottbrenner/cfn-lint-action:main`
or
`uses: docker://ghcr.io/scottbrenner/cfn-lint-action:v2`

**Comment by NickLiffen** [comment]
okay @barryhagan I am sure we can get that done 💯

**Comment by NickLiffen** [comment]
To explain more ... the new version should install quicker, but we can also publish a docker image (if you like). I never saw a use case because the new version was installed from a tag so much quicker. However, if you would like a docker version, there is no reason we can't use one.

**Comment by ScottBrenner** [comment]
Agree with @NickLiffen above, reference https://docs.github.com/en/actions/creating-actions/about-actions#types-of-actions. Previous versions of the pre-built are kept for backwards compatibility reasons, to support those who's workflows are using it.
